networks:
  nginx:
    external: true

services:

  portfolio:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    container_name: "portfolio"
    environment:
      VIRTUAL_HOST: dlyhub.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: dlyhub.com
      LETSENCRYPT_EMAIL: ${DEFAULT_EMAIL}
    networks:
      - nginx