name: Create Branch from Issue

on:
  issues:
    types: [opened, assigned]

jobs:
  call-create-branch:
    uses: skuskusku13/devops/.github/workflows/reusable-create-branch.yml@main
    secrets:
      CREATE_BRANCH_TOKEN: ${{ secrets.CREATE_BRANCH_TOKEN }}
    permissions:
      contents: write
      issues: write
